### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Castle.Facilities.Quartz#23]
@kristofdc I've moved the Quartz facility from the castleproject-deprecated GitHub organisation over to the main organisation, and set up AppVeyor (https://ci.appveyor.com/project/castleproject/castle-facilities-quartz/history) on our castleproject account. Thanks again for getting those changes sorted.

With Castle Core and Windsor we maintain a changelog file in the repository root, it would be great if we could do that here too before releasing 0.5.0.

Could you put a pull request together with that. The readme also needs some polish too.

**Comment by kristofdc** [comment]
Hey @jonorossi I have (again) troubles after creating pull request --> cannot be merged automatically.
Isn't it easier to delete my fork and start over again to add changelog/readme/documentation?

**Comment by jonorossi** [comment]
> Hey @jonorossi I have (again) troubles after creating pull request --> cannot be merged automatically.
> Isn't it easier to delete my fork and start over again to add changelog/readme/documentation?

You'll need to make sure master is pointing at upstream's master to include the recent changes, or yes just recreate your fork.

**Comment by jonorossi** [comment]
Fixed by #24.
