### ISSUE TITLE
How to use code configuration

### ISSUE THREAD

**Issue by lun3322** [castleproject/Castle.Facilities.Quartz#26]
Do not use xml

**Comment by tasoss** [comment]
What do you mean?As far as i have read the xml is required.
Am i missing something?
I'm just trying to use quartz with windsor.

**Comment by tasoss** [comment]
@jonorossi  thanks for the info!

**Comment by mario-d-s** [comment]
@kristofdc has added a C# API in #28.

@lun3322, @tasoss  Can you please read over the [documentation](https://github.com/castleproject/Castle.Facilities.Quartz/blob/master/docs/configuration.md) and tell us what you think?
