### ISSUE TITLE
support 3.0.4.0?

### ISSUE THREAD

**Issue by lun3322** [castleproject/Castle.Facilities.Quartz#27]
未经处理的异常:  System.IO.FileLoadException: 未能加载文件或程序集“Quartz, Version=3.0.2.0, Culture=neutral, PublicKeyToken=f6b8c98a402cc8a4”或它的某一个依赖项。找到的程序集
清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
   在 Castle.Facilities.Quartz.QuartzFacility.Init()
   在 Castle.MicroKernel.Facilities.AbstractFacility.Castle.MicroKernel.IFacility.Init(IKernel kernel, IConfiguration facilityConfig)
   在 Castle.MicroKernel.DefaultKernel.AddFacility(String key, IFacility facility)
   在 Castle.MicroKernel.DefaultKernel.AddFacility(IFacility facility)
   在 Castle.Windsor.WindsorContainer.AddFacility(IFacility facility)
   在 Castle.Windsor.Installer.DefaultComponentInstaller.SetUpFacilities(IConfiguration[] configurations, IWindsorContainer container, IConversionManager converter)
   在 Castle.Windsor.Installer.DefaultComponentInstaller.SetUp(IWindsorContainer container, IConfigurationStore store)
   在 Castle.Windsor.WindsorContainer.RunInstaller()
   在 Castle.Windsor.WindsorContainer..ctor(IConfigurationInterpreter interpreter)
   在 ConsoleApplication1.Program.Main(String[] args) 位置 E:\work\dotnet\Tests\Solution1\ConsoleApplication1\Program.cs:行号 22

**Comment by Liwoj** [comment]
As the 3.0.4 is only minor version of Quartz with no breaking API changes, simple `bindingRedirect` in app\web config should be fine until updated facility is released.

```
<dependentAssembly>
	<assemblyIdentity name="Quartz" publicKeyToken="f6b8c98a402cc8a4" culture="neutral" />
	<bindingRedirect oldVersion="0.0.0.0-3.0.4.0" newVersion="3.0.4.0" />
</dependentAssembly>
```
